server:
  port: 8081
  servlet:
    context-path: /sky



mybatis:
  type-aliases-package: com.marshall.sky.user.model
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sky?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: wrglive2016
    driver-class-name: com.mysql.cj.jdbc.Driver