server:
  port: 8081


mybatis:
  type-aliases-package: com.marshall.sky.user.model
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: sky-cloud-user
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 47.105.157.44:9300
      repositories:
        enabled: true
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  datasource:
    url: jdbc:mysql://localhost:3306/sky?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: wrglive2016
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    password: wrglive2016
    host: 47.105.157.44
    port: 6379
    lettuce:
      pool:
        #最大线程数
        max-active: 8
        #阻塞时间
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池最小连接数 默认0
        min-idle: 1



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

ribbon:
  eureka:
    enabled: true
